### PR TITLE
Simplify Janus config and rules

### PR DESCRIPTION
**Pull request by huddlej**
This PR simplifies the logic of Snakemake rules by moving augur- and fauna-specific logic into the configuration file or into those applications themselves. It also simplifies the format of the configuration file in several ways:

  - Config entries are flat instead of hierarchical
  - All prepare and process options are specified through a single entry in a given build and passed directly to the corresponding script's command line
  - Config entries are all named
  - Config entries support string templates and combinatorial products of variables (e.g., all combinations of lineages and resolutions)

In the case of the simplest pathogen builds, the config is just:

```json
{
    "name": "zika",
    "virus": "zika"
}
```

Pathogens that all share the same simple builds can be combined into a single config entry. Any list of values can be expanded into a string by referencing the list's attribute (e.g., `virus` below) as a Python string template.

```json
{
    "name": "{virus}",
    "virus": ["zika", "ebola"]
}
```

String templates enable a single build template to define multiple builds that all use the same shared configuration parameters.

```json
{
    "name": "dengue_{lineage}",
    "virus": "dengue",
    "lineage": ["all", "denv1", "denv2", "denv3", "denv4"],
    "process": "--no_titers"
}
```

The most complicated builds can use string templates to parameterize lineage-specific inputs. The following example defines all combinations of seasonal flu builds in a single flat rule with lineage-specific sequence and titer inputs.

```json
{
    "name": "{virus}_{lineage}_{segment}_{resolution}",
    "description": "Live flu builds",
    "virus": ["flu"],
    "lineage": ["h3n2", "h1n1pdm", "vic", "yam"],
    "segment": ["ha"],
    "resolution": ["3y", "6y", "12y"],
    "prepare": "--sequences ../../../fauna/data/{lineage}.fasta --titers ../../../fauna/data/{lineage}_hi_titers.tsv --complete_frequencies"
}
```

### CODE REVIEW

**Comment by trvrb** [comment]
@huddlej ---

This is looking really good. I think the expansion of a list like `"resolution": ["3y", "6y", "12y"]` into `{resolution}` is super smart. Really excellent spec.

Small thing: can we use something other than `name`? I'd like to converge on a single term for this thing. Name feels too vague. It's `file_prefix` in augur. It's `dataset` in auspice. Let's pick a replacement now and then propagate to other parts of the app.

Okay... just spoke with John about this. `bundle_id` seemed like the best term we could immediately come up with, but there may be something better.

**Comment by trvrb** [comment]
Thought about this a bit more and I think I'd propose going with `stem` as in:
```
{
    "stem": "dengue_{lineage}",
    "virus": "dengue",
    "lineage": ["all", "denv1", "denv2", "denv3", "denv4"],
    "process": "--no_titers"
}
```
We can refer to `file_stem` in augur, etc... Should be pretty clear.

**Comment by trvrb** [comment]
@huddlej ---

I started on testing this and got everything installed and got it to run, but ran into an error when calling `./janus download`. I get the following:

```
Downloading data for zika
/bin/bash: -c: line 0: syntax error near unexpected token `>'
/bin/bash: -c: line 0: ` source activate janus_python2;  cd fauna && python download_all.py --virus zika --sequences --titers &>> /Users/trvrb/Documents/src/janus/log/fauna_download.log '
Error in rule download:
    jobid: 0
    log: log/fauna_download.log

RuleException:
CalledProcessError in line 120 of /Users/trvrb/Documents/src/janus/Snakefile:
Command ' source activate janus_python2;  cd fauna && python download_all.py --virus zika --sequences --titers &>> /Users/trvrb/Documents/src/janus/log/fauna_download.log ' returned non-zero exit status 2.
  File "/Users/trvrb/Documents/src/janus/Snakefile", line 120, in __rule_download
  File "/Users/trvrb/miniconda3/envs/janus_python3/lib/python3.6/concurrent/futures/thread.py", line 55, in run
Exiting because a job execution failed. Look above for error message
Will exit after finishing currently running jobs.
Exiting because a job execution failed. Look above for error message
Complete log: .snakemake/log/2017-10-24T103947.537824.snakemake.log
```

I confirmed that I can run each of these commands individually outside of snakemake (`source activate janus_python2`, `cd fauna`, `python download_all.py --virus zika --sequences --titers`). Any insight here? We can sit down and look at this together if helpful.

**Comment by trvrb** [comment]
Running now... looks generally great. In testing a few things came up:

1. The command `./janus download --config filters="zika"` makes sense to me in what it's doing, while the current command `./janus --config filters="zika"` seems opaque. I'd change this to `./janus build --config filters="zika"`. This especially makes sense given you also use `push`.

2. Are there other `--config` options besides `filters`? Would be cleaner to just call `./janus download --filters zika ebola` as is normal in argparse. I recognize that snakemake might require passing things through `config` in which case, the present behavior is okay.

3. The initial run of `./janus download --config filters="zika"` works fine. Then if I run this again I get `Nothing to be done`. This is expected, but I still get `Nothing to be done` if I manually delete the file `janus/fauna/data/zika.fasta`. The option `--forceall` does force the download. But it should realize when the file is missing.

4. Printing shell commands that are called to std out would give more comfort that everything is happening as it should.

5. Great to have log files. However, the log file `log/process_zika.log` doesn't appear to be filling with stdout piped from the `zika.process.py` until after the job has completed. Is there anyway to fix this? Again, this would make using janus more trustworthy.

6. The push to staging works great.

This is excellent work. Thank you John.

**Comment by huddlej** [comment]
Thanks, @trvrb. I don't have great solutions to each of these comments, but below is my best attempt to address each one. Probably the most important part is the `download` behavior which we could talk about more in person.

> The command ./janus download --config filters="zika" makes sense to me in what it's doing, while the current command ./janus download --config filters="zika" seems opaque. I'd change this to ./janus build --config filters="zika". This especially makes sense given you also use push.

I’ve renamed the original default rule from “all” to “build”, so you can now type:

```bash
./janus build
```

to run all builds. I’ve updated the README to reflect this change. Running janus without specifying `build` will still also run all builds, but that is no longer the documented way to run it.

> Are there other --config options besides filters? Would be cleaner to just call ./janus download --filters zika ebola as is normal in argparse. I recognize that snakemake might require passing things through config in which case, the present behavior is okay.

The `--config` interface is part of Snakemake and is the standard way to modify an existing configuration from the command line. Running a Snakemake file with `--config filters="zika,ebola"` is the same as modifying the `config.json` file to look like this.

```json
{
    "filters": "zika,ebola",
    "builds": [
    ]
}
```

I could add a `-f` option to the janus shell script as a shorthand for the full config flag, but then the janus script begins to do more than just load the right environment and run snakemake.

I already feel like the `-l`  flag to run snakemake locally is a little confusing in that its the only flag you pass to janus that isn’t passed through to snakemake. Another way to get a similar effect to `-l` would be to check for the presence of a `qsub` or `sbatch` binary on the path and only run snakemake locally when one of those can’t be found. This way when you run on a laptop, you always get local runs, but when you run on rhino you always get cluster runs.

> The initial run of ./janus download --config filters="zika" works fine. Then if I run this again I get Nothing to be done. This is expected, but I still get Nothing to be done if I manually delete the file janus/fauna/data/zika.fasta. The option --forceall does force the download. But it should realize when the file is missing.

The `Nothing to be done` message is a bug. The `download` rule should always re-download everything associated with the viruses in your requested builds whether or not the files already exist. That issue is fixed now.

The correct way to make snakemake realize a file is missing is to make the file a defined output of one rule (for instance, the `download` rule) and an input of another rule (like the `prepare` rule). Right now, the `download` rule is actually a “dummy” rule. It only runs when you specifically invoke it and it’s not explicitly part of the dependency graph at all. As a user, you just have to know that you need to download your data before running augur.

It’s either hard or impossible to make snakemake aware of fauna files because there isn’t a consistent one-to-one mapping between augur inputs and fauna outputs for each virus. Zika, Ebola, mumps all have a single FASTA named after the virus, but avian flu has one FASTA file per segment, dengue has one file per serotype plus titers, and flu has multiple possible FASTA and titers input combinations.

Maybe one way around this would be to keep the simple download rule for the case when a virus maps to a single FASTA file and then add virus-specific rules for more complex cases. Then the augur rules could dynamically build the list of inputs they need from the config file and snakemake would invoke the appropriate rules to build those inputs on the fly.

> Printing shell commands that are called to std out would give more comfort that everything is happening as it should.
> 
> Great to have log files. However, the log file log/process_zika.log doesn't appear to be filling with stdout piped from the zika.process.py until after the job has completed. Is there anyway to fix this? Again, this would make using janus more trustworthy.

This is a frustrating operating system problem. When stdout and stderr are being written to a non-terminal output like a file, the operating system sets the default output buffer to a larger size than on terminal windows where the buffer is flushed for each line. Even using `tee` to write to a file and standard out at the same time produces the same large buffer behavior on rhino.

There is a standard GNU utility called `stdbuf` that can force the standard buffer of a specific application to write out in a different mode. The `stdbuf` command is available on Ubuntu through GNU coreutils. It isn’t installed on OS X by default, but there is a homebrew coreutils package that would make it available. There is a conda package for coreutils maintained by the BioConda group, but it doesn’t seem to be properly maintained.

How would you feel about adding coreutils as a dependency to janus that would be managed by the user and not the install script?

**Comment by trvrb** [comment]
@huddlej ---

Thanks for the detailed responses. I agree with proceeding with the changes you've made.

* Thanks for adding the `build` command line option.
* I'd like to think more about a `-f` flag. This seems like a common use case, where almost always you're running janus to just build a single pathogen that streamlining seems helpful. However, I understand that this cuts against the grain of the snakemake setup. Nothing wrong with keeping the current `--config` behavior and adding a shortcut on top of this at some later point if we see fit.
* Let's discuss the download issue in person and how best to tackle it.
* Don't worry about the standard out buffer issue. I hadn't realized it was such a low-level thing.

**Pull request merged**
